zeros:
  joint11: 0
  joint12: 0
  joint13: 0
  joint14: 0
  joint15: 0
  joint16: 0
  joint17: 0
  bottom11: 0
  joint21: 0
  joint22: 0
  joint23: 0
  joint24: 0
  joint25: 0
  joint26: 0
  joint27: 0
  top21prime: 0
  joint31: 0
  joint32: 0
  joint33: 0
  joint34: 0
  joint35: 0
  joint36: 0
  joint37: 0
  top21: 0
  joint41: 0
  joint42: 0
  joint43: 0
  joint44: 0
  joint45: 0
  joint46: 0
  joint47: 0
  bottom11prime: 0
